package Spring_Hibernate_XML_Annotations.Dao;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;

import org.springframework.stereotype.Component;

import Spring_Hibernate_XML_Annotations.Dto.Account;
import Spring_Hibernate_XML_Annotations.Dto.Employee;

@Component
public class EmployeeDao {

	EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("Nikhil");
	EntityManager entityManager = entityManagerFactory.createEntityManager();
	EntityTransaction entityTransaction = entityManager.getTransaction();

	public void saveEmployee(Employee employee) {
		entityTransaction.begin();
		entityManager.persist(employee);
		entityTransaction.commit();

	}

	public void fetchAllEmployee() {
		Query query = entityManager.createQuery("SELECT e FROM Employee e");
		List<Employee> list = query.getResultList();
		System.out.println(list);
	}

	public void fetchEmployee(int eid) {
		Employee employee = entityManager.find(Employee.class, eid);
		System.out.println(employee);

	}

	public void deleteEmployee(int eid) {
		Employee employee = entityManager.find(Employee.class, eid);

		if (employee != null) {
			entityTransaction.begin();
			entityManager.remove(employee);
			entityTransaction.commit();
		} else {
			System.out.println("Employee with id : " + eid + " does not exixts !!");
		}
	}

	public void update(int eid, Employee employee) {
		Employee dbemployee = entityManager.find(Employee.class, eid);
        //As the id is autogenerated we have to set the id of account also thought we have used the cascade
		if (dbemployee != null) {
			employee.setId(eid);
			employee.getAccount().setId(dbemployee.getAccount().getId());
		//	employee.getAccount().setId(3); //will update employee and account will get inserted !!

			entityTransaction.begin();
			entityManager.merge(employee);
			entityTransaction.commit();
		} else {
			System.out.println("Employee with id : " + eid + " does not exixts !!");
		}
	}
}
